<a href="https://colab.research.google.com/github/AtufaMehboob59/Multiple_Disease_Prediction/blob/main/Multiple_disease_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import library

import pandas as pd

In [2]:
# read datset

df = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/MultipleDiseasePrediction.csv')

In [3]:
df.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection

In [4]:
df.prognosis.value_counts()

prognosis
Fungal infection                           120
Allergy                                    120
GERD                                       120
Chronic cholestasis                        120
Drug Reaction                              120
Peptic ulcer diseae                        120
AIDS                                       120
Diabetes                                   120
Gastroenteritis                            120
Bronchial Asthma                           120
Hypertension                               120
Migraine                                   120
Cervical spondylosis                       120
Paralysis (brain hemorrhage)               120
Jaundice                                   120
Malaria                                    120
Chicken pox                                120
Dengue                                     120
Typhoid                                    120
hepatitis A                                120
Hepatitis B                                120
Hepatitis C                                120
Hepatitis D                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Impetigo                                   120
Name: count, dtype: int64

In [5]:
df.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
      dtype='object', length=133)

In [6]:
df.shape

(4920, 133)

In [7]:
# define x and y

x = df.drop(['prognosis'], axis=1)

y = df['prognosis']

In [8]:
# train test split

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [9]:
# model selection

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [10]:
log_reg = LogisticRegression()
knn = KNeighborsClassifier()
dt = DecisionTreeClassifier()
rf = RandomForestClassifier()

In [11]:
# train model

log = log_reg.fit(x_train, y_train)
knn = knn.fit(x_train, y_train)
dt = dt.fit(x_train, y_train)
rf = rf.fit(x_train, y_train)

In [12]:
# prediction

pred_log = log.predict(x_test)
pred_knn = knn.predict(x_test)
pred_dt = dt.predict(x_test)
pred_rf = rf.predict(x_test)

In [13]:
# evaluation

from sklearn.metrics import  classification_report

cr1 = classification_report(y_test, pred_log)
cr2 = classification_report(y_test, pred_knn)
cr3 = classification_report(y_test, pred_dt)
cr4 = classification_report(y_test, pred_rf)

print("Logistic Regression\n")
print(cr1)
print("______________________***********_________________________\n")


print("KNN\n")
print(cr2)
print("______________________***********_________________________\n")


print("Decision Tree\n")
print(cr3)
print("______________________***********_________________________\n")


print("Random Forest\n")
print(cr4)
print("______________________***********_________________________\n")

Logistic Regression

                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        18
                                   AIDS       1.00      1.00      1.00        30
                                   Acne       1.00      1.00      1.00        24
                    Alcoholic hepatitis       1.00      1.00      1.00        25
                                Allergy       1.00      1.00      1.00        24
                              Arthritis       1.00      1.00      1.00        23
                       Bronchial Asthma       1.00      1.00      1.00        33
                   Cervical spondylosis       1.00      1.00      1.00        23
                            Chicken pox       1.00      1.00      1.00        21
                    Chronic cholestasis       1.00      1.00      1.00        15
                            Common Cold       1.00      1.00      1.00        23
                                 Dengue       1.00      1.00      1.00        26
                              Diabetes        1.00      1.00      1.00        21
           Dimorphic hemmorhoids(piles)       1.00      1.00      1.00        29
                          Drug Reaction       1.00      1.00      1.00        24
                       Fungal infection       1.00      1.00      1.00        19
                                   GERD       1.00      1.00      1.00        28
                        Gastroenteritis       1.00      1.00      1.00        25
                           Heart attack       1.00      1.00      1.00        23
                            Hepatitis B       1.00      1.00      1.00        27
                            Hepatitis C       1.00      1.00      1.00        26
                            Hepatitis D       1.00      1.00      1.00        23
                            Hepatitis E       1.00      1.00      1.00        29
                          Hypertension        1.00      1.00      1.00        25
                        Hyperthyroidism       1.00      1.00      1.00        24
                           Hypoglycemia       1.00      1.00      1.00        26
                         Hypothyroidism       1.00      1.00      1.00        21
                               Impetigo       1.00      1.00      1.00        24
                               Jaundice       1.00      1.00      1.00        19
                                Malaria       1.00      1.00      1.00        22
                               Migraine       1.00      1.00      1.00        25
                        Osteoarthristis       1.00      1.00      1.00        22
           Paralysis (brain hemorrhage)       1.00      1.00      1.00        24
                    Peptic ulcer diseae       1.00      1.00      1.00        17
                              Pneumonia       1.00      1.00      1.00        28
                              Psoriasis       1.00      1.00      1.00        22
                           Tuberculosis       1.00      1.00      1.00        25
                                Typhoid       1.00      1.00      1.00        19
                Urinary tract infection       1.00      1.00      1.00        26
                         Varicose veins       1.00      1.00      1.00        22
                            hepatitis A       1.00      1.00      1.00        34

                               accuracy                           1.00       984
                              macro avg       1.00      1.00      1.00       984
                           weighted avg       1.00      1.00      1.00       984

______________________***********_________________________

KNN

                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        18
                                   AIDS       1.00      1.00      1.00        30
                                   Acne       1.00      1.00      1.00        24
                    Alcoholic hepatitis       1.00      1.00      1.00        25
                                Allergy       1.00      1.00      1.00        24
                              Arthritis       1.00      1.00      1.00        23
                       Bronchial Asthma       1.00      1.00      1.00        33
                   Cervical spondylosis       1.00      1.00      1.00        23
                            Chicken pox       1.00      1.00      1.00        21
                    Chronic cholestasis       1.00      1.00      1.00        15
                            Common Cold       1.00      1.00      1.00        23
                                 Dengue       1.00      1.00      1.00        26
                              Diabetes        1.00      1.00      1.00        21
           Dimorphic hemmorhoids(piles)       1.00      1.00      1.00        29
                          Drug Reaction       1.00      1.00      1.00        24
                       Fungal infection       1.00      1.00      1.00        19
                                   GERD       1.00      1.00      1.00        28
                        Gastroenteritis       1.00      1.00      1.00        25
                           Heart attack       1.00      1.00      1.00        23
                            Hepatitis B       1.00      1.00      1.00        27
                            Hepatitis C       1.00      1.00      1.00        26
                            Hepatitis D       1.00      1.00      1.00        23
                            Hepatitis E       1.00      1.00      1.00        29
                          Hypertension        1.00      1.00      1.00        25
                        Hyperthyroidism       1.00      1.00      1.00        24
                           Hypoglycemia       1.00      1.00      1.00        26
                         Hypothyroidism       1.00      1.00      1.00        21
                               Impetigo       1.00      1.00      1.00        24
                               Jaundice       1.00      1.00      1.00        19
                                Malaria       1.00      1.00      1.00        22
                               Migraine       1.00      1.00      1.00        25
                        Osteoarthristis       1.00      1.00      1.00        22
           Paralysis (brain hemorrhage)       1.00      1.00      1.00        24
                    Peptic ulcer diseae       1.00      1.00      1.00        17
                              Pneumonia       1.00      1.00      1.00        28
                              Psoriasis       1.00      1.00      1.00        22
                           Tuberculosis       1.00      1.00      1.00        25
                                Typhoid       1.00      1.00      1.00        19
                Urinary tract infection       1.00      1.00      1.00        26
                         Varicose veins       1.00      1.00      1.00        22
                            hepatitis A       1.00      1.00      1.00        34

                               accuracy                           1.00       984
                              macro avg       1.00      1.00      1.00       984
                           weighted avg       1.00      1.00      1.00       984

______________________***********_________________________

Decision Tree

                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        18
                                   AIDS       1.00      1.00      1.00        30
                                   Acne       1.00      1.00      1.00        24
                    Alcoholic hepatitis       1.00      1.00      1.00        25
                                Allergy       1.00      1.00      1.00        24
                              Arthritis       1.00      1.00      1.00        23
                       Bronchial Asthma       1.00      1.00      1.00        33
                   Cervical spondylosis       1.00      1.00      1.00        23
                            Chicken pox       1.00      1.00      1.00        21
                    Chronic cholestasis       1.00      1.00      1.00        15
                            Common Cold       1.00      1.00      1.00        23
                                 Dengue       1.00      1.00      1.00        26
                              Diabetes        1.00      1.00      1.00        21
           Dimorphic hemmorhoids(piles)       1.00      1.00      1.00        29
                          Drug Reaction       1.00      1.00      1.00        24
                       Fungal infection       1.00      1.00      1.00        19
                                   GERD       1.00      1.00      1.00        28
                        Gastroenteritis       1.00      1.00      1.00        25
                           Heart attack       1.00      1.00      1.00        23
                            Hepatitis B       1.00      1.00      1.00        27
                            Hepatitis C       1.00      1.00      1.00        26
                            Hepatitis D       1.00      1.00      1.00        23
                            Hepatitis E       1.00      1.00      1.00        29
                          Hypertension        1.00      1.00      1.00        25
                        Hyperthyroidism       1.00      1.00      1.00        24
                           Hypoglycemia       1.00      1.00      1.00        26
                         Hypothyroidism       1.00      1.00      1.00        21
                               Impetigo       1.00      1.00      1.00        24
                               Jaundice       1.00      1.00      1.00        19
                                Malaria       1.00      1.00      1.00        22
                               Migraine       1.00      1.00      1.00        25
                        Osteoarthristis       1.00      1.00      1.00        22
           Paralysis (brain hemorrhage)       1.00      1.00      1.00        24
                    Peptic ulcer diseae       1.00      1.00      1.00        17
                              Pneumonia       1.00      1.00      1.00        28
                              Psoriasis       1.00      1.00      1.00        22
                           Tuberculosis       1.00      1.00      1.00        25
                                Typhoid       1.00      1.00      1.00        19
                Urinary tract infection       1.00      1.00      1.00        26
                         Varicose veins       1.00      1.00      1.00        22
                            hepatitis A       1.00      1.00      1.00        34

                               accuracy                           1.00       984
                              macro avg       1.00      1.00      1.00       984
                           weighted avg       1.00      1.00      1.00       984

______________________***********_________________________

Random Forest

                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        18
                                   AIDS       1.00      1.00      1.00        30
                                   Acne       1.00      1.00      1.00        24
                    Alcoholic hepatitis       1.00      1.00      1.00        25
                                Allergy       1.00      1.00      1.00        24
                              Arthritis       1.00      1.00      1.00        23
                       Bronchial Asthma       1.00      1.00      1.00        33
                   Cervical spondylosis       1.00      1.00      1.00        23
                            Chicken pox       1.00      1.00      1.00        21
                    Chronic cholestasis       1.00      1.00      1.00        15
                            Common Cold       1.00      1.00      1.00        23
                                 Dengue       1.00      1.00      1.00        26
                              Diabetes        1.00      1.00      1.00        21
           Dimorphic hemmorhoids(piles)       1.00      1.00      1.00        29
                          Drug Reaction       1.00      1.00      1.00        24
                       Fungal infection       1.00      1.00      1.00        19
                                   GERD       1.00      1.00      1.00        28
                        Gastroenteritis       1.00      1.00      1.00        25
                           Heart attack       1.00      1.00      1.00        23
                            Hepatitis B       1.00      1.00      1.00        27
                            Hepatitis C       1.00      1.00      1.00        26
                            Hepatitis D       1.00      1.00      1.00        23
                            Hepatitis E       1.00      1.00      1.00        29
                          Hypertension        1.00      1.00      1.00        25
                        Hyperthyroidism       1.00      1.00      1.00        24
                           Hypoglycemia       1.00      1.00      1.00        26
                         Hypothyroidism       1.00      1.00      1.00        21
                               Impetigo       1.00      1.00      1.00        24
                               Jaundice       1.00      1.00      1.00        19
                                Malaria       1.00      1.00      1.00        22
                               Migraine       1.00      1.00      1.00        25
                        Osteoarthristis       1.00      1.00      1.00        22
           Paralysis (brain hemorrhage)       1.00      1.00      1.00        24
                    Peptic ulcer diseae       1.00      1.00      1.00        17
                              Pneumonia       1.00      1.00      1.00        28
                              Psoriasis       1.00      1.00      1.00        22
                           Tuberculosis       1.00      1.00      1.00        25
                                Typhoid       1.00      1.00      1.00        19
                Urinary tract infection       1.00      1.00      1.00        26
                         Varicose veins       1.00      1.00      1.00        22
                            hepatitis A       1.00      1.00      1.00        34

                               accuracy                           1.00       984
                              macro avg       1.00      1.00      1.00       984
                           weighted avg       1.00      1.00      1.00       984

______________________***********_________________________